
name: demo-action
on:
  push:
    branches: test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-steps
        uses: actions/checkout@v4.2.2
      - name: printmessgae
        run: echo "Hello team"
      - name: Delete the repo
        uses: f1lander/delete-repository-action@v2.2
        with:
          # github username or organization
          owner: AnupUST
          # name of repository to delete
          repo: AnupUST/checkaction
          # access token with repo scope
          token: ${{ secrets.DEL_REPO }}
