name: demo-action
on:
  push:
    branches: test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-steps
        uses: actions/checkout@v4.2.2
      - name: printmessgae
        run: echo "Hello team"
      - name : CreatDockerImage
        run :
            sudo docker build -t nginximg  .
            sudo docker run nginx -d -p 3000:3000 nginximg

      
          
  
