name: demo-action
on:
   workflow_dispatch:
 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-steps
        uses: actions/checkout@v4.2.2
      - name: printmessgae
        run: echo "Hello team"
      - name: test access
        run : curl -H "Authorization:account-token " https://api.github.com/repos/AnupUST/checkaction
      

      
          
  
